# Generated by Django 5.1.2 on 2024-10-08 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField()),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.TextField()),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.tarefa')),
            ],
        ),
    ]
