# Generated by Django 5.1.2 on 2024-10-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotempo',
            name='horas_trabalhadas',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
