# Generated by Django 5.1.2 on 2024-10-08 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_registrotempo_data_registro'),
        ('tarefas', '0002_alter_tarefa_usuario_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotempo',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_de_tempo', to='tarefas.tarefa'),
        ),
    ]
