# Generated by Django 5.1.2 on 2024-10-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_alter_registrotempo_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotempo',
            name='horas_trabalhadas',
            field=models.IntegerField(),
        ),
    ]
